# Generated by Django 4.1.3 on 2023-05-31 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('image', models.CharField(max_length=300, verbose_name='Imagem')),
                ('views', models.IntegerField(default=0)),
                ('bulletin_url', models.URLField(blank=True, max_length=300, verbose_name='URL do Arquivo')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('image', models.CharField(max_length=300, verbose_name='Imagem')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('image', models.CharField(max_length=300, verbose_name='Imagem')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('function', models.CharField(max_length=200, verbose_name='Função')),
                ('image', models.CharField(max_length=300, verbose_name='Foto')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='genre',
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.RemoveField(
            model_name='review',
            name='album',
        ),
        migrations.RemoveField(
            model_name='review',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='review',
            name='magazine',
        ),
        migrations.RemoveField(
            model_name='reviewtrack',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewtrack',
            name='track',
        ),
        migrations.DeleteModel(
            name='Teste',
        ),
        migrations.RemoveField(
            model_name='track',
            name='parent_album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Magazine',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='ReviewTrack',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(to='bulletins.tag'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='bulletins.category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='tags',
            field=models.ManyToManyField(to='bulletins.tag'),
        ),
    ]
