# Generated by Django 4.1.3 on 2023-05-31 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0002_bulletin_category_partners_tag_team_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partners',
            new_name='Partner',
        ),
        migrations.RenameModel(
            old_name='Team',
            new_name='TeamMember',
        ),
        migrations.AlterModelOptions(
            name='bulletin',
            options={'ordering': ['-id'], 'verbose_name': 'Boletim', 'verbose_name_plural': 'Boletins'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['name'], 'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['name'], 'verbose_name': 'Membro', 'verbose_name_plural': 'Equipe'},
        ),
    ]
