# Generated by Django 4.1.3 on 2023-05-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0003_rename_partners_partner_rename_team_teammember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='tags',
            field=models.ManyToManyField(blank=True, to='bulletins.tag'),
        ),
        migrations.AlterField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(blank=True, to='bulletins.tag'),
        ),
    ]
