# Generated by Django 4.1.3 on 2023-06-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0005_bulletin_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação'),
        ),
    ]
