# Generated by Django 4.1.3 on 2023-06-01 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0006_alter_bulletin_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tags',
        ),
    ]
