# Generated by Django 4.1.3 on 2023-06-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0007_remove_category_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='created_at',
            field=models.DateTimeField(verbose_name='Data de Publicação'),
        ),
    ]
