# Generated by Django 4.1.3 on 2023-06-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0009_alter_category_description_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='image',
            field=models.CharField(default='https://i.postimg.cc/9MByQPbr/default-bulletins.png', max_length=300, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.CharField(default='https://i.postimg.cc/8cjsgL08/default-profile.png', max_length=300, verbose_name='Foto'),
        ),
    ]
