# Generated by Django 4.1.3 on 2023-06-01 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0010_alter_bulletin_image_alter_teammember_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
