# Generated by Django 4.1.3 on 2023-06-07 04:48

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0012_alter_bulletin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to='img/bulletins/', verbose_name='Imagem'),
        ),
    ]
