# Generated by Django 4.1.3 on 2023-06-07 05:05

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0013_alter_bulletin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='bulletin_url',
            field=models.URLField(blank=True, help_text='Link do arquivo no Google Drive', max_length=300, verbose_name='URL do Arquivo'),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', help_text='Formato: 1920x2714', keep_meta=True, quality=-1, scale=None, size=[1920, 2714], upload_to='img/bulletins/', verbose_name='Imagem'),
        ),
    ]
