# Generated by Django 4.1.3 on 2023-06-07 23:34

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0020_teammember_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('image', django_resized.forms.ResizedImageField(crop=None, default='img/action/default.png', force_format='JPEG', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='img/action/', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'ordering': ['name'],
            },
        ),
    ]
