# Generated by Django 4.1.3 on 2023-06-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0021_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
