# Generated by Django 4.1.3 on 2023-06-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0022_subscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['name'], 'verbose_name': 'ação', 'verbose_name_plural': 'ações'},
        ),
        migrations.AlterModelOptions(
            name='bulletin',
            options={'ordering': ['-id'], 'verbose_name': 'boletim', 'verbose_name_plural': 'boletins'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['name'], 'verbose_name': 'colaborador', 'verbose_name_plural': 'colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='subscribers',
            options={'ordering': ['name'], 'verbose_name': 'inscrito', 'verbose_name_plural': 'inscritos'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['name'], 'verbose_name': 'membro', 'verbose_name_plural': 'equipe'},
        ),
    ]
