# Generated by Django 4.1.3 on 2023-06-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0023_alter_action_options_alter_bulletin_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
