# Generated by Django 4.1.3 on 2023-06-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0025_alter_bulletin_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='s', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='slug',
            field=models.SlugField(),
        ),
    ]
