# Generated by Django 4.1.3 on 2023-06-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0027_alter_bulletin_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
