# Generated by Django 4.1.3 on 2023-06-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0033_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
