# Generated by Django 4.1.3 on 2023-06-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0034_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
