# Generated by Django 4.1.3 on 2023-06-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0035_alter_bulletin_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nome'),
        ),
    ]
