# Generated by Django 4.1.3 on 2023-06-23 01:34

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0036_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='subscription_token',
            field=django_cryptography.fields.encrypt(models.CharField(default='a', max_length=50, unique=True)),
            preserve_default=False,
        ),
    ]
